logging:
  enabled: false
  level: 10 # 10 = debug, 50 = critical
paths:
  cg: "/dev/captain-grant/" # path from CG repo
  src: "/Downloads/" # folder to take human JSON from
  cgteams: "/dev/captain-grant/teams/" #path to teams fo