logging:
  enabled: false
  level: 10 # 10 = debug, 50 = critical
paths:
  # os.path.join treats strings that start with / as absolute paths, so leading slash
  # has been omitted
  cg: "dev/captain-grant/" # path from CG repo
  cgteams: "teams/" #path to teams fo
  src: "Downloads/" # folder to take human JSON from